<a href="https://colab.research.google.com/github/adi10032003/AWS-/blob/main/DATA_ANALYSIS_PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
print("Om ganganpatye namah jay shri ram")

Om ganganpatye namah jay shri ram


In [15]:
import numpy as np
l1=[1,2,3,4,5]
a=np.array(l1)
a


array([1, 2, 3, 4, 5])

In [16]:
np.random.randint(10)
a=np.random.randint(100,size=(3))

In [17]:
a.max()

np.int64(64)

**Array**

In [18]:
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[-1])
print(arr[-3:-1])
print(arr[-3:])
print(arr[:-1])

1
5
[3 4]
[3 4 5]
[1 2 3 4]


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [20]:
a1=np.array([1,2,3,4,5])


In [21]:
np.zeros(10)
np.ones(10)
np.full(10,5)
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [22]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
import pandas as pd
import numpy as np

In [24]:
list1=[1,2,3,4]
indexing=['a','b','c','d']
pd.Series(list1,indexing)

a    1
b    2
c    3
d    4
dtype: int64

In [25]:
np.random.seed(10)

In [26]:
df=pd.read_csv('/content/Crime_Data_from_2020_to_Present.csv')
df
df.shape

<ipython-input-26-aad3c5f0eed5>:1: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/content/Crime_Data_from_2020_to_Present.csv')


(56893, 28)

In [27]:
df.head(10)
df.columns
df['DR_NO']
df['DR_NO'].max()
df['DR_NO'].min()
df['DR_NO'].mean()
#conditional select
df[df.DR_NO==190326475]

DR_NO               Date Rptd                DATE OCC  TIME OCC  AREA  \
0  190326475  03/01/2020 12:00:00 AM  03/01/2020 12:00:00 AM      2130     7   

  AREA NAME  Rpt Dist No  Part 1-2  Crm Cd       Crm Cd Desc  ... Status  \
0  Wilshire          784         1     510  VEHICLE - STOLEN  ...     AA   

    Status Desc Crm Cd 1 Crm Cd 2  Crm Cd 3 Crm Cd 4  \
0  Adult Arrest    510.0    998.0       NaN      NaN   

                                  LOCATION Cross Street      LAT       LON  
0  1900 S  LONGWOOD                     AV          NaN  34.0375 -118.3506  

[1 rows x 28 columns]

Creating dataframe using dictionary


In [28]:
d={'name':['aditya'],'age':[22]}
d
df=pd.DataFrame(d)
df
df.shape

(1, 2)